version: '3.2'
services:
  web:
      build:
        context: .
        dockerfile: ./containers/nginx/Dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
  php:
      build:
        context: .
        dockerfile: ./containers/php/Dockerfile
      volumes:
        # - ./code:/var/www/html
        # - .code:/var/www/html
        # - /mnt/c/git/docker-nginx-phpfpm/code:/var/www/html
        - type: bind
          source: ./code
          target: /var/www/html
